services:
  - type: web
    name: voice-authenticator
    env: node
    plan: free
    buildCommand: npm install --no-optional && pip install -r requirements.txt && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
